version: '3.8'
services:
  library-app-auth:
    image: damou/library-app-auth:dev
    container_name: library-app-auth-container
    volumes:
      - .:/var/www/html/
    ports:
      - "8080:80"
    networks:
      - library-app-network

  library-app-auth-db:
    image: mongo:latest
    container_name: library-app-auth-db
    hostname: mongodb
    volumes:
      - ./database/seeders/:/data
    ports:
      - "27018:27017"
    networks:
      - library-app-network

networks:
  library-app-network:
    driver: bridge
    name: library-app-network
